apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tool-quickstatements.fullname" . }}
  labels:
{{ include "tool-quickstatements.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tool-quickstatements.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tool-quickstatements.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PLATFORM_MW_BACKEND_HOST
              value: {{ .Values.platform.mediawikiBackendHost | quote }}
            - name: PHP_SESSION_SAVE_HANDLER
              value: {{ .Values.php.sessionSaveHandler | quote }}
            {{- if .Values.php.sessionSavePath }}
            - name: PHP_SESSION_SAVE_PATH
              value: {{ .Values.php.sessionSavePath | quote }}
            {{- else if eq .Values.php.sessionSaveHandler "redis" }}
            - name: PHP_SESSION_SAVE_HANDLER_REDIS_HOST
              value: {{ .Values.php.sessionSaveRedisHost | quote }}
            - name: PHP_SESSION_SAVE_HANDLER_REDIS_PORT
              value: {{ .Values.php.sessionSaveRedisPort | quote }}
            - name: PHP_SESSION_SAVE_HANDLER_REDIS_DATABASE
              value: {{ .Values.php.sessionSaveRedisDatabase | quote }}
            - name: PHP_SESSION_SAVE_HANDLER_REDIS_AUTH
            {{- if .Values.php.sessionSaveRedisAuth }}
              value: {{ .Values.php.sessionSaveRedisAuth | quote }}
            {{- end }}
            {{- if .Values.php.sessionSaveRedisAuthSecretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.php.sessionSaveRedisAuthSecretName | quote }}
                  key: {{ .Values.php.sessionSaveRedisAuthSecretKey | quote }}
            {{- end }}
            - name: PHP_SESSION_SAVE_HANDLER_REDIS_PREFIX
              value: {{ .Values.php.sessionSaveRedisPrefix | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          # TODO this is just nginx so we should have some sort of liveness probe?
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
